services:
  database:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  # web_api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - database
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  parsers:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - .:/app
    command: python3 /app/data_parsers/main.py

    

volumes:
  postgres_data:
